version: '3.8'

services:
  nginx:
    build:
      context: ./build/nginx
    restart: always
    volumes:
      - ./symfony:/var/www/symfony
      - ./angular/dist:/var/www/angular
      - ./logs/nginx:/var/log/nginx:cached
    environment:
      APP_ENV: dev
    depends_on:
      - php
    ports:
      - 80:80
      - 443:443
    networks:
      - masrecetas

  php:
    build:
      context: .
      dockerfile: build/php/Dockerfile
      args:
        TIMEZONE: ${TIMEZONE}
    environment:
      APP_ENV: dev
    volumes:
      - ./symfony/:/var/www/symfony/
      - ./logs/symfony:/var/www/symfony/var/log:cached
    expose:
      - 9000
    networks:
      - masrecetas

  node:
    build:
      context: .
      dockerfile: build/node/Dockerfile
    volumes:
      - ./angular:/var/www/angular:cached
      - /var/www/angular/node_modules/
    ports:
      - 4200:4200
    networks:
      - masrecetas

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - my-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - masrecetas

volumes:
  my-db:

networks:
  masrecetas:
