add_recipe:
    path: /api/add
    controller: App\Controller\RecipeHasIngredientController::create
    methods: [POST]

edit_recipe:
    path: /api/edit
    controller: App\Controller\RecipeHasIngredientController::edit
    methods: [POST]

show_recipe:
    path: /api/show/{recipe_id}
    controller: App\Controller\RecipeHasIngredientController::getRecipeHasIngredient
    methods: [GET]

show_category:
    path: /api/category
    controller: App\Controller\RecipeController::getCategory
    methods: [GET]

show_ultimate_recipe:
    path: /api/ultimate/recipes/{number}
    controller: App\Controller\RecipeController::getUltimateRecipes
    methods: [GET]

upload_file:
    path: /api/upload/file
    controller: App\Controller\RecipeController::uploadFile
    methods: [POST]

remote_file:
    path: /api/remote/file
    controller: App\Controller\RecipeController::remoteFile
    methods: [POST]
