index:
    path: /api/
    controller: App\Controller\DefaultController::index

add_recipe:
    path: /api/add
    controller: App\Controller\RecipeHasIngredientController::create
    methods: [POST]

show_ultimate_recipe:
    path: /api/ultimate/recipes/{number}
    controller: App\Controller\RecipeController::getUltimateRecipes
    methods: [GET]
